// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlideBuilder.Infrastructure.Persistence;

#nullable disable

namespace SlideBuilder.Infrastructure.Migrations
{
    [DbContext(typeof(SlideBuilderDbContext))]
    partial class SlideBuilderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("SlideBuilder.Core.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StageCompleted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("IX_ConversationMessages_ProjectId_CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.ConversationSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CoveringMessagesFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoveringMessagesTo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CoveringMessagesFrom")
                        .HasDatabaseName("IX_ConversationSummaries_ProjectId_Range");

                    b.ToTable("ConversationSummaries");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentSummary")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSummary")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Outline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlidesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeckId")
                        .IsUnique();

                    b.ToTable("Outlines");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.OutlineRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutlineId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlidesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TriggeredByMessageId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredByMessageId");

                    b.HasIndex("OutlineId", "RevisionNumber")
                        .HasDatabaseName("IX_OutlineRevisions_OutlineId_RevisionNumber");

                    b.ToTable("OutlineRevisions");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Revision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutlineSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlidesSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StyleBriefSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Revisions");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Slide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentBlocksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeakerNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Slides");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.StyleBrief", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeckId")
                        .IsUnique();

                    b.ToTable("StyleBriefs");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Asset", b =>
                {
                    b.HasOne("SlideBuilder.Core.Domain.Project", null)
                        .WithMany("Assets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Checkpoint", b =>
                {
                    b.HasOne("SlideBuilder.Core.Domain.Job", null)
                        .WithMany("Checkpoints")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.ConversationMessage", b =>
                {
                    b.HasOne("SlideBuilder.Core.Domain.Project", null)
                        .WithMany("Messages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.ConversationSummary", b =>
                {
                    b.HasOne("SlideBuilder.Core.Domain.Project", "Project")
                        .WithMany("ConversationSummaries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Deck", b =>
                {
                    b.HasOne("SlideBuilder.Core.Domain.Project", null)
                        .WithOne("Deck")
                        .HasForeignKey("SlideBuilder.Core.Domain.Deck", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Job", b =>
                {
                    b.HasOne("SlideBuilder.Core.Domain.Project", null)
                        .WithMany("Jobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Outline", b =>
                {
                    b.HasOne("SlideBuilder.Core.Domain.Deck", null)
                        .WithOne("DraftOutline")
                        .HasForeignKey("SlideBuilder.Core.Domain.Outline", "DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.OutlineRevision", b =>
                {
                    b.HasOne("SlideBuilder.Core.Domain.Outline", "Outline")
                        .WithMany("Revisions")
                        .HasForeignKey("OutlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlideBuilder.Core.Domain.ConversationMessage", "TriggeredByMessage")
                        .WithMany()
                        .HasForeignKey("TriggeredByMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Outline");

                    b.Navigation("TriggeredByMessage");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Revision", b =>
                {
                    b.HasOne("SlideBuilder.Core.Domain.Project", null)
                        .WithMany("Revisions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Slide", b =>
                {
                    b.HasOne("SlideBuilder.Core.Domain.Deck", null)
                        .WithMany("Slides")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.StyleBrief", b =>
                {
                    b.HasOne("SlideBuilder.Core.Domain.Deck", null)
                        .WithOne("DraftStyleBrief")
                        .HasForeignKey("SlideBuilder.Core.Domain.StyleBrief", "DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Deck", b =>
                {
                    b.Navigation("DraftOutline");

                    b.Navigation("DraftStyleBrief");

                    b.Navigation("Slides");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Job", b =>
                {
                    b.Navigation("Checkpoints");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Outline", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("SlideBuilder.Core.Domain.Project", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ConversationSummaries");

                    b.Navigation("Deck");

                    b.Navigation("Jobs");

                    b.Navigation("Messages");

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
